addResponseIndicator("tags", "taglist", "tagslist", "alltags");

function tagsListResponse(message) {
    DMessage("TagsList: BeginningResponse");
    if (getResponsesDisabled()) {
        DMessage("TagsList: EndResponse Response is Disabled");
        return false;
    }
    let tagsList = "(*) after a category means required. Example tag: \"tag n p sh sf\""
    tagsList += "  \n| DressState*: ";
    tagsList += "  Naked(n)";
    tagsList += "  HalfDressed(hd)";
    tagsList += "  Dressed(d)";
    tagsList += "  GarmetCovering(gc)";
    tagsList += "  HandsCovering(h)";
    tagsList += "  SeeThrough(st)";
    tagsList += "  |\n| Visible Body Parts:";
    tagsList += "  WetPussy(wp)";
    tagsList += "  CreamyPussy(cp)";
    tagsList += "  DrippingPussy(dp)";
    tagsList += "  Pussy(p)";
    tagsList += "  Boobs(b or t)";
    tagsList += "  Ass(a)";
    tagsList += "  CumCoveredAss(cca)";
    tagsList += "  CumCoveredBoobs(ccb)";
    tagsList += "  CumCoveredCock(ccc)";
    tagsList += "  CumCoveredFace(ccfa)";
    tagsList += "  CumCoveredFeet(ccf)";
    tagsList += "  CumCoveredFingers(ccfi)";
    tagsList += "  CumCoveredLegs(cca)";
    tagsList += "  CumCoveredPussy(ccp)";
    tagsList += "  Face(f)";
    tagsList += "  Fingers(fgs or fs)";
    tagsList += "  Feet(ft)";
    tagsList += "  Legs(l)";
    tagsList += "  Cock(ck)";
    tagsList += "  |\n| Body Type:";
    tagsList += "  Blonde(bl)";
    tagsList += "  Brunette(bru or bro)";
    tagsList += "  RedHead(red or re)";
    tagsList += "  Slim(sl)";
    tagsList += "  Thick(th)";
    tagsList += "  |\n| Category*:";
    tagsList += "  AllFours(allf)";
    tagsList += "  CumCovered(cc)";
    tagsList += "  Hardcore(hc)";
    tagsList += "  Softcore(sc)";
    tagsList += "  Lesbian(ls)";
    tagsList += "  FemDom(fd)";
    tagsList += "  LezDom(ld)";
    tagsList += "  Gay(g)";
    tagsList += "  MaleDom(md)";
    tagsList += "  Captions(c)";
    tagsList += "  PointOfView(pov)";
    tagsList += "  Bondage(bd or bg)";
    tagsList += "  Shower(sh)";
    tagsList += "  Bath(bt or bh)";
    tagsList += "  Outdoors(out or od or os)";
    tagsList += "  |\n| People Involved*:";
    tagsList += "  SoloFemale(sf)";
    tagsList += "  SoloMale(sm)";
    tagsList += "  Couple(cpl)";
    tagsList += "  2Female(2f or f2)";
    tagsList += "  3Female(3f or f3)";
    tagsList += "  2Male(2m or m2)";
    tagsList += "  3Male(3m or m3)";
    tagsList += "  2Male1Female(2m1f or 1f2m)";
    tagsList += "  2Female1Male(2f1m or 1m2f)";
    tagsList += "  Orgy([any amt of people not listed before](o))";
    tagsList += "  |\n| Action:";
    tagsList += "  BlowJob(bj)";
    tagsList += "  Masturbating(m)";
    tagsList += "  Sucking(s)";
    tagsList += "  HandJob(hj)";
    tagsList += "  Fingering(fg)";
    tagsList += "  Rubbing(rb)";
    tagsList += "  Licking(lk)";
    tagsList += "  FaceSitting(fs)";
    tagsList += "  Missionary(ms or sx)";
    tagsList += "  DoggyStyle(ds)";
    tagsList += "  CowGirl(cg)";
    tagsList += "  Standing(sd or sg)";
    tagsList += "  Anal(an or al)";
    tagsList += "  GangBang(gb)";
    tagsList += "  Glaring(gla)";
    tagsList += "  Smiling(smi)";
    tagsList += "  |\n| View:";
    tagsList += "  SideView(sv)";
    tagsList += "  CloseUp(cu)";

    tagsList += "  |\n| Accessory:";

    tagsList += "  Dildo(dd or dl)";
    tagsList += "  Vibrator(v)";
    tagsList += "  Panties(pt or py)";
    tagsList += "  WetPanties(wpant or wpa or wpt)";
    tagsList += "  Piercing(prc)";
    tagsList += "  Bra(br)";
    tagsList += "  BathingSuit(ss)";
    DMessage(tagsList, 0);
    DMessage("TagsList: EndResponse");
    return true;
}