run("chatutils.js");
DMessage("Setting up chat");
setUpChat();
run("mediautils.js");
DMessage("Setting up media");
setUpMedia();
run("personalityutils.js");
DMessage("Setting up personality");
setUpVars();
run("Structure" + java.io.File.separator + "MischeviousStructure.js");
