DMessage("png vampire: Beginning");
CMessage("Sometimes I feel like a vampire");
CMessage("But instead of your blood, I feed on your ache! %Grin%");
CMessage("Tasting all its flavours");
CMessage("Always different");
CMessage("Sometimes it's pain flavoured");
CMessage("Sometimes it's frustration");
CMessage("Almost always there is a hint of lust");
CMessage("And an overwhelming taste of pleasure %Grin%");
CMessage("Because we both know you love all the things I do to you");
CMessage("And you don't just let me feast on you");
CMessage("%No%, you can't live without me %EmoteHappy%");
CMessage("But I'm not a parasite");
CMessage("I'm more a symbiont");
CMessage("We both benefit from it after all");
CMessage("You bring me pleasure and power");
CMessage("And I make you stronger");
CMessage("More submissive");
CMessage("More obedient");
CMessage("Giving you purpose in life");
CMessage("And making you a perfect %PetName% %Grin%");
CMessage("And right now, I need a snack...");
customStroking("So let's get you %Stroking% for me %lol%");
//Info: The dom describes your relation as a Symbiosis that feeds her and makes you a better person
DMessage("png vampire: End");