sendMessage("%Subname%...");
sendMessage("I know you enjoy this, otherwise you wouldn't be here");
sendMessage("But I know that sometimes");
sendMessage("There will be a part of you that wants to run");
sendMessage("A very primal part of your manhood that fears the surrender");
sendMessage("And trembles at the ache I'm filling you with");
sendMessage("Urging you to run, to seek shelter and be safe");
sendMessage("It's okay to feel that sometimes");
sendMessage("But when you feel that rising up inside you");
sendMessage("I want you to fight it");
sendMessage("Fight the urge to run and hide");
sendMessage("To make yourself safe");
sendMessage("I want you to walk out into the open");
sendMessage("Naked");
sendMessage("Exposed");
sendMessage("And completely throbbing");
sendMessage("And I want you to beg me to keep you from feeling safe");
sendMessage("And no matter how unnatural those words feel coming out of your mouth");
sendMessage("When I tell you to wrap your hand around that tortured cock");
sendMessage("And you feel how hard it gets at my words");
sendMessage("You'll know that you'll never be safe from me");
sendMessage("And you'll never WANT to be %Grin%");
Stroking();