CMessage("%Subname%...");
CMessage("I know you enjoy this, otherwise you wouldn't be here");
CMessage("But I know that sometimes");
CMessage("There will be a part of you that wants to run");
CMessage("A very primal part of your manhood that fears the surrender");
CMessage("And trembles at the ache I'm filling you with");
CMessage("Urging you to run, to seek shelter and be safe");
CMessage("It's okay to feel that sometimes");
CMessage("But when you feel that rising up inside you");
CMessage("I want you to fight it");
CMessage("Fight the urge to run and hide");
CMessage("To make yourself safe");
CMessage("I want you to walk out into the open");
CMessage("Naked");
CMessage("Exposed");
CMessage("And completely throbbing");
CMessage("And I want you to beg me to keep you from feeling safe");
CMessage("And no matter how unnatural those words feel coming out of your mouth");
CMessage("When I tell you to wrap your hand around that tortured cock");
CMessage("And you feel how hard it gets at my words");
CMessage("You'll know that you'll never be safe from me");
CMessage("And you'll never <i>want<> to be %Grin%");
Stroking();