CMessage("%stopstroking%", 0);
stopStroking();
CMessage("You know, if you're being honest with yourself");
CMessage("Deep down there has to be a part of you that knows this is wrong");
CMessage("Physically, I mean");
CMessage("That your body wasn't meant to work this way");
CMessage("Your %Cock% wasn't meant to ache so much");
CMessage("And your balls just weren't meant to hold so much cum");
CMessage("I mean");
CMessage("Stroking is supposed to feel GOOD, right? %Lol%");
CMessage("But instead, well");
CMessage("Why don't you edge for me real quick and see for yourself");
startEdging();
CMessage("%stopstrokingedge%");
CMessage("%lettheedgefade%");
CMessage("See what I mean though?");
CMessage("Sometimes I think I've got you so worked up you can't even think straight %Lol%");
CMessage("And if I'm being honest with MYSELF");
CMessage("It turns me on so much knowing what I can do to you");
CMessage("And what I can make you do to yourself %Grin%");
CMessage("Like those poor, sensitive balls for instance @CBTBalls");
CMessage("I mean, fuck...");
CMessage("Balls were ABSOLUTELY not meant to be treated that way");
CMessage("And yet, you do it just because I want you to %EmoteHappy%");
CMessage("You'll suffer any way I want");
CMessage("And that makes me feel sexier than you can possibly imagine");
CMessage("And I promise you");
CMessage("I'm %Gonna% make sure your %Cock% feels every ounce of my arousal");
CMessage("Every degree of my heat");
CMessage("And every bit of my wickedness");
CMessage("I just can't promise it will enjoy it %Grin%");