sendMessage("%stopstroking%", 0);
stopStroking();
sendMessage("You know, if you're being honest with yourself");
sendMessage("Deep down there has to be a part of you that knows this is wrong");
sendMessage("Physically, I mean");
sendMessage("That your body wasn't meant to work this way");
sendMessage("Your %Cock% wasn't meant to ache so much");
sendMessage("And your balls just weren't meant to hold so much cum");
sendMessage("I mean");
sendMessage("Stroking is supposed to feel GOOD, right? %Lol%");
sendMessage("But instead, well");
sendMessage("Why don't you %edge% for me real quick and see for yourself");
startEdging();
sendMessage("%lettheedgefade%");
sendMessage("See what I mean though?");
sendMessage("Sometimes I think I've got you so worked up you can't even think straight %Lol%");
sendMessage("And if I'm being honest with MYSELF");
sendMessage("It turns me on so much knowing what I can do to you");
sendMessage("And what I can make you do to yourself %Grin%");
sendMessage("Like those poor, sensitive balls for instance @CBTBalls");
sendMessage("I mean, fuck...");
sendMessage("Balls were ABSOLUTELY not meant to be treated that way");
sendMessage("And yet, you do it just because I want you to %EmoteHappy%");
sendMessage("You'll suffer any way I want");
sendMessage("And that makes me feel sexier than you can possibly imagine");
sendMessage("And I promise you");
sendMessage("I'm %Gonna% make sure your %Cock% feels every ounce of my arousal");
sendMessage("Every degree of my heat");
sendMessage("And every bit of my wickedness");
sendMessage("I just can't promise it will enjoy it %Grin%");